EliteInternationDemoWebAPP/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using  System.ComponentModel.DataAnnotations.Schema;
using System.Web.UI.WebControls;

namespace EliteInternationDemoWebAPP.Models
{
    public class Vehicle
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int VehicleId { get; set; }
        [Display(Name ="Model / Vehicle Name:"),Required(ErrorMessage = "Please Give a Vehicle Name")]
        public string Model { get; set; }
        [DataType(DataType.Date),Required(ErrorMessage = "Set the Registration Date")]
        public DateTime Registraion { get; set; }

        [Required,Display(Name = "Engine Capacity")]
        public float EngineCapacity { get; set; }
        [Required, DataType(DataType.Currency)]
        public decimal Price { get; set; }
        [Required, Display(Name = "Steer Position")]
        public int SteerTypeId { get; set; }
        [Required]
        public float MileAges { get; set; }
        [Required,Display(Name = "Gear Type")]
        public int GearTypeId { get; set; }
        [Required,Display(Name = "Fuel type")]
        public int FuelTypeId { get; set; }
        [Required,Display(Name = "Color Of Vehicle")]
        public int ColorOfVehicleId { get; set; }
        public int VehicleTypeId { get; set; }
        [ForeignKey("VehicleTypeId")]
        public virtual  TypeOfVehicle TypeOfVehicle { get; set; }
        [ForeignKey("SteerTypeId")]
        public virtual  SteerType SteerType { get; set; }
        [ForeignKey("GearTypeId")]
        public virtual  GearType GearType { get; set; }
        [ForeignKey("FuelTypeId")]
        public virtual FuelType FuelType { get; set; }
        [ForeignKey("ColorOfVehicleId")]
        public virtual  ColorOfVehilce ColorOfVehilce { get; set; }

    }

   
}

EliteInternationDemoWebAPP/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EliteInternationDemoWebAPP.Models;
using EliteInternationDemoWebAPP.Context;

namespace EliteInternationDemoWebAPP.Controllers
{
    public class VehicleController : Controller
    {
        private VehicleDbContext db = new VehicleDbContext();

        // GET: /Vehicle/
        public ActionResult Index()
        {
            var vehicles = db.Vehicles.Include(v => v.ColorOfVehilce).Include(v => v.FuelType).Include(v => v.GearType).Include(v => v.SteerType).Include(v => v.TypeOfVehicle);
            foreach (var aVehicle in vehicles)
            {
                var firstOrDefault = db.VehicleImages.FirstOrDefault(x => x.VehicleId == aVehicle.VehicleId);
                if (firstOrDefault != null)
                {
                    var aVehicleImage=  firstOrDefault.VehicleImages;
                    string name = aVehicle.VehicleId.ToString();
                    ViewData[name] = "data:Image/png;base64," +
                                                              Convert.ToBase64String(aVehicleImage);
                }
            }
            return View(vehicles.ToList());
        }

        // GET: /Vehicle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: /Vehicle/Create
        public ActionResult Create()
        {
            ViewBag.ColorOfVehicleId = new SelectList(db.ColorOfVehilces, "ColorOfVehicleId", "ColorOfVehicleName");
            ViewBag.FuelTypeId = new SelectList(db.FuelTypes, "FuelTypeId", "FuelTypeName");
            ViewBag.GearTypeId = new SelectList(db.GearTypes, "GearTypeId", "GearTypeName");
            ViewBag.SteerTypeId = new SelectList(db.SteerTypes, "SteerTypeId", "SteerTypeName");
            ViewBag.VehicleTypeId = new SelectList(db.TypesOfVehicles, "VehicleTypeId", "VehicleTypeName");
            return View();
        }

        // POST: /Vehicle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="VehicleId,Model,Registraion,EngineCapacity," +
        "Price,SteerTypeId,MileAges,GearTypeId,FuelTypeId,ColorOfVehicleId,VehicleTypeId")]
         Vehicle vehicle, IEnumerable<HttpPostedFileBase> httpPostedFileBases)
        {
            IEnumerable<HttpPostedFileBase> httpPostedFile = httpPostedFileBases;
           
            if (ModelState.IsValid)
            {
                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                if (httpPostedFile != null)
                {
                    foreach (var afile in httpPostedFile)
                    {
                        VehicleImage aVehicleImage = new VehicleImage();
                        Stream stream = afile.InputStream;
                        BinaryReader brd = new BinaryReader(stream);
                        byte[] bytes = brd.ReadBytes((int) stream.Length);
                        aVehicleImage.VehicleId = vehicle.VehicleId;
                        aVehicleImage.VehicleImages = bytes;
                        db.VehicleImages.Add(aVehicleImage);
                        db.SaveChanges();

                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.ColorOfVehicleId = new SelectList(db.ColorOfVehilces, "ColorOfVehicleId", "ColorOfVehicleName", vehicle.ColorOfVehicleId);
            ViewBag.FuelTypeId = new SelectList(db.FuelTypes, "FuelTypeId", "FuelTypeName", vehicle.FuelTypeId);
            ViewBag.GearTypeId = new SelectList(db.GearTypes, "GearTypeId", "GearTypeName", vehicle.GearTypeId);
            ViewBag.SteerTypeId = new SelectList(db.SteerTypes, "SteerTypeId", "SteerTypeName", vehicle.SteerTypeId);
            ViewBag.VehicleTypeId = new SelectList(db.TypesOfVehicles, "VehicleTypeId", "VehicleTypeName", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: /Vehicle/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            ViewBag.ColorOfVehicleId = new SelectList(db.ColorOfVehilces, "ColorOfVehicleId", "ColorOfVehicleName", vehicle.ColorOfVehicleId);
            ViewBag.FuelTypeId = new SelectList(db.FuelTypes, "FuelTypeId", "FuelTypeName", vehicle.FuelTypeId);
            ViewBag.GearTypeId = new SelectList(db.GearTypes, "GearTypeId", "GearTypeName", vehicle.GearTypeId);
            ViewBag.SteerTypeId = new SelectList(db.SteerTypes, "SteerTypeId", "SteerTypeName", vehicle.SteerTypeId);
            ViewBag.VehicleTypeId = new SelectList(db.TypesOfVehicles, "VehicleTypeId", "VehicleTypeName", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // POST: /Vehicle/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="VehicleId,Model,Registraion,EngineCapacity,Price,SteerTypeId,MileAges,GearTypeId,FuelTypeId,ColorOfVehicleId,VehicleTypeId")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ColorOfVehicleId = new SelectList(db.ColorOfVehilces, "ColorOfVehicleId", "ColorOfVehicleName", vehicle.ColorOfVehicleId);
            ViewBag.FuelTypeId = new SelectList(db.FuelTypes, "FuelTypeId", "FuelTypeName", vehicle.FuelTypeId);
            ViewBag.GearTypeId = new SelectList(db.GearTypes, "GearTypeId", "GearTypeName", vehicle.GearTypeId);
            ViewBag.SteerTypeId = new SelectList(db.SteerTypes, "SteerTypeId", "SteerTypeName", vehicle.SteerTypeId);
            ViewBag.VehicleTypeId = new SelectList(db.TypesOfVehicles, "VehicleTypeId", "VehicleTypeName", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: /Vehicle/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: /Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            IEnumerable<VehicleImage> vehicleImages = db.VehicleImages.Where(x => x.VehicleId == id);
            db.VehicleImages.RemoveRange(vehicleImages);
            db.SaveChanges();
            if (vehicle != null) db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EliteInternationDemoWebAPP/Controllers/VehicleImageController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EliteInternationDemoWebAPP.Models;
using EliteInternationDemoWebAPP.Context;

namespace EliteInternationDemoWebAPP.Controllers
{
    public class VehicleImageController : Controller
    {
        private VehicleDbContext db = new VehicleDbContext();

        // GET: /VehicleImage/
        public ActionResult Index()
        {
            var vehicleimages = db.VehicleImages.Include(v => v.Vehicle);
            return View(vehicleimages.ToList());
        }

        // GET: /VehicleImage/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IEnumerable<VehicleImage> vehicleImages = db.VehicleImages.Where(x => x.VehicleId == id);
            ViewBag.vehicleImages = vehicleImages;
            Vehicle aVehicle = db.Vehicles.FirstOrDefault(x => x.VehicleId == id);
            if (aVehicle == null)
            {
                return HttpNotFound();
            }
            return View(aVehicle);
        }

        // GET: /VehicleImage/Create
        public ActionResult Create()
        {
            ViewBag.VehicleId = new SelectList(db.Vehicles, "VehicleId", "Model");
            return View();
        }

        // POST: /VehicleImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="VehicleImageId,VehicleImages,VehicleId")] VehicleImage vehicleimage)
        {
            if (ModelState.IsValid)
            {
                db.VehicleImages.Add(vehicleimage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VehicleId = new SelectList(db.Vehicles, "VehicleId", "Model", vehicleimage.VehicleId);
            return View(vehicleimage);
        }

        // GET: /VehicleImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleImage vehicleimage = db.VehicleImages.Find(id);
            if (vehicleimage == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleId = new SelectList(db.Vehicles, "VehicleId", "Model", vehicleimage.VehicleId);
            return View(vehicleimage);
        }

        // POST: /VehicleImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="VehicleImageId,VehicleImages,VehicleId")] VehicleImage vehicleimage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicleimage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VehicleId = new SelectList(db.Vehicles, "VehicleId", "Model", vehicleimage.VehicleId);
            return View(vehicleimage);
        }

        // GET: /VehicleImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleImage vehicleimage = db.VehicleImages.Find(id);
            if (vehicleimage == null)
            {
                return HttpNotFound();
            }
            return View(vehicleimage);
        }

        // POST: /VehicleImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VehicleImage vehicleimage = db.VehicleImages.Find(id);
            db.VehicleImages.Remove(vehicleimage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EliteInternationDemoWebAPP/Views/Vehicle/Create.cshtml
@model EliteInternationDemoWebAPP.Models.Vehicle

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Vehicle", FormMethod.Post, 
new { id = "VehicleCreateForm", name = "VehicleCreateForm", enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Model, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model)
                @Html.ValidationMessageFor(model => model.Model)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Registraion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registraion)
                @Html.ValidationMessageFor(model => model.Registraion)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EngineCapacity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineCapacity)
                @Html.ValidationMessageFor(model => model.EngineCapacity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MileAges, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MileAges)
                @Html.ValidationMessageFor(model => model.MileAges)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SteerTypeId, "SteerTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SteerTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.SteerTypeId)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GearTypeId, "GearTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GearTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.GearTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FuelTypeId, "FuelTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FuelTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.FuelTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorOfVehicleId, "ColorOfVehicleId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ColorOfVehicleId", String.Empty)
                @Html.ValidationMessageFor(model => model.ColorOfVehicleId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleTypeId, "VehicleTypeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleTypeId", String.Empty)
                @Html.ValidationMessageFor(model => model.VehicleTypeId)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Image File",new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="httpPostedFileBases"  name="httpPostedFileBases" multiple />
                @Html.ValidationMessage("httpPostedFileBases")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EliteInternationDemoWebAPP/Views/Vehicle/Delete.cshtml
@model EliteInternationDemoWebAPP.Models.Vehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ColorOfVehilce.ColorOfVehicleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColorOfVehilce.ColorOfVehicleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuelType.FuelTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuelType.FuelTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GearType.GearTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GearType.GearTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SteerType.SteerTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SteerType.SteerTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfVehicle.VehicleTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfVehicle.VehicleTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Registraion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registraion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EngineCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngineCapacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MileAges)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MileAges)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EliteInternationDemoWebAPP/Views/Vehicle/Details.cshtml
@model EliteInternationDemoWebAPP.Models.Vehicle

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicle</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ColorOfVehilce.ColorOfVehicleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColorOfVehilce.ColorOfVehicleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuelType.FuelTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuelType.FuelTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GearType.GearTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GearType.GearTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SteerType.SteerTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SteerType.SteerTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfVehicle.VehicleTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfVehicle.VehicleTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Registraion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registraion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EngineCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngineCapacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MileAges)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MileAges)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EliteInternationDemoWebAPP/Views/Vehicle/Index.cshtml
@model IEnumerable<EliteInternationDemoWebAPP.Models.Vehicle>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ColorOfVehilce.ColorOfVehicleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FuelType.FuelTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GearType.GearTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SteerType.SteerTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfVehicle.VehicleTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Registraion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EngineCapacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MileAges)
        </th>
        <th> Image</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ColorOfVehilce.ColorOfVehicleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FuelType.FuelTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GearType.GearTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SteerType.SteerTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfVehicle.VehicleTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Registraion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EngineCapacity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MileAges)
        </td>
        <td>
            <img src="@ViewData[item.VehicleId.ToString()]" width="100" height="100"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit",new { id=item.VehicleId }) |
            <a href="@Url.Action("Details","VehicleImage",new{id=item.VehicleId})">Details</a> |
            @Html.ActionLink("Delete", "Delete", new { id=item.VehicleId })
        </td>
    </tr>
}

</table>